ALTER TABLE Account ADD CONSTRAINT 
fk_account_person FOREIGN KEY (PersonId)
REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Game ADD CONSTRAINT
fk_game_opp_account FOREIGN KEY(Opp_GamerTag)
REFERENCES Account(GamerTag) ON UPDATE CASCADE;

ALTER TABLE Game ADD CONSTRAINT
fk_game_user_account FOREIGN KEY(Account_GamerTag)
REFERENCES Account(GamerTag) ON UPDATE CASCADE;

ALTER TABLE User_Has_Card ADD CONSTRAINT
fk_card_user FOREIGN KEY (Account_Gamertag)
REFERENCES Account(GamerTag) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE User_Has_Card ADD CONSTRAINT
fk_user_has_card FOREIGN KEY(CardId)
REFERENCES Card(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Card ADD CONSTRAINT
fk_card_cardset FOREIGN KEY (CardSet)
REFERENCES Cardset(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Card ADD CONSTRAINT
fk_card_cardtype FOREIGN KEY (CardType)
REFERENCES CardType(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Card ADD CONSTRAINT
fk_card_rarity FOREIGN KEY(Rarity)
REFERENCES Rarity(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Card ADD CONSTRAINT
fk_card_race FOREIGN KEY(Race)
REFERENCES Race(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Card ADD CONSTRAINT
fk_card_class FOREIGN KEY(CardClass)
REFERENCES CardClass(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Deck_Has_Card ADD CONSTRAINT
fk_card_deck FOREIGN KEY(Card_id)
REFERENCES Card(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Deck_Has_Card ADD CONSTRAINT
fk_deck_has_card FOREIGN KEY(Deck_id)
REFERENCES Deck(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE User_Has_Deck ADD CONSTRAINT
fk_deck_user FOREIGN KEY(Account_Gamertag)
REFERENCES Account(Gamertag) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE User_Has_Deck ADD CONSTRAINT
fk_user_has_deck FOREIGN KEY(DeckId)
REFERENCES Deck(id) ON DELETE CASCADE ON UPDATE CASCADE;