INSERT INTO Cardset VALUES (2, 'Core', null);
INSERT INTO Cardset VALUES (3, 'Classic', null);
INSERT INTO Cardset VALUES (4, 'Special Core', null);
INSERT INTO Cardset VALUES (5, 'Introductory Tutorial', null);
INSERT INTO Cardset VALUES (7, 'Placeholder', null);
INSERT INTO Cardset VALUES (8, 'Perform Effect', null);
INSERT INTO Cardset VALUES (11, 'Promotion Card', null);
INSERT INTO Cardset VALUES (12, 'Curse of Naxxramas', 2014-07-22);
INSERT INTO Cardset VALUES (13, 'Goblins vs Gnomes', 2014-12-08);
INSERT INTO Cardset VALUES (14, 'Blackrock Mountain', 2015-04-02);
INSERT INTO Cardset VALUES (15, 'The Grand Tournament', 2015-08-24);
INSERT INTO Cardset VALUES (16, 'Game Creators', null);
INSERT INTO Cardset VALUES (17, 'Heroes And Powers', null);
INSERT INTO Cardset VALUES (18, 'Brawl Specials', null);
INSERT INTO Cardset VALUES (20, 'League of Explorers', 2015-11-13);
INSERT INTO Rarity VALUES (1, 'Common');
INSERT INTO Rarity VALUES (2, 'Core and Collectible');
INSERT INTO Rarity VALUES (3, 'Rare');
INSERT INTO Rarity VALUES (4, 'Epic');
INSERT INTO Rarity VALUES (5, 'Legendary');
INSERT INTO CardType VALUES(3, 'Hero');
INSERT INTO CardType VALUES(4, 'Minion');
INSERT INTO CardType VALUES(5, 'Spell');
INSERT INTO CardType VALUES(6, 'Effect');
INSERT INTO CardType VALUES(7, 'Weapon');
INSERT INTO CardClass VALUES(0, 'Neutral');
INSERT INTO CardClass VALUES(2, 'Druid');
INSERT INTO CardClass VALUES(3, 'Hunter');
INSERT INTO CardClass VALUES(4, 'Mage');
INSERT INTO CardClass VALUES(5, 'Paladin');
INSERT INTO CardClass VALUES(6, 'Priest');
INSERT INTO CardClass VALUES(7, 'Rogue');
INSERT INTO CardClass VALUES(8, 'Shaman');
INSERT INTO CardClass VALUES(9, 'Warlock');
INSERT INTO CardClass VALUES(10, 'Warrior');
INSERT INTO CardClass VALUES(11, 'Ysera');
INSERT INTO Race VALUES(20, 'Beast');
INSERT INTO Race VALUES(15, 'Demon');
INSERT INTO Race VALUES(14, 'Murloc');
INSERT INTO Race VALUES(23, 'Pirate');
INSERT INTO Race VALUES(24, 'Dragon');
INSERT INTO Race VALUES(17, 'Mech');
INSERT INTO Race VALUES(21, 'Totem');

